networks:
  dev:
    driver: bridge
services:

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: api
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - dev

  api:
    image: ghcr.io/mindenit/api:main
    restart: always
    environment:
      - ASPNETCORE_HTTP_PORTS=5035
      - DISCORD_WEBHOOK_URL=your_url
    ports:
      - 4173:5035
    depends_on:
      - db
    networks:
      - dev