networks:
  dev:
    driver: bridge

services:
  api:
    image: api
    restart: always
    environment:
      - ASPNETCORE_HTTP_PORTS=5035
    ports:
      - 4173:5035
    depends_on:
      - db
    networks:
      - dev
 
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: api
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - 5432:5432
    networks:
      - dev
 
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_LISTEN_PORT: 8080
      PGADMIN_DEFAULT_EMAIL: example@gmail.com
      PGADMIN_DEFAULT_PASSWORD: example
    ports:
      - 5000:8080
    networks:
      - dev